import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "app/app/Header";
import { Footer } from "app/app/Footer";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";


const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextUIProvider> 
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </NextUIProvider>
    </html>
  );
}
